(function () {
  "use strict";
  const { buildAttachment, formatPrompt, normalizeThreadInfo } = window.MemoNexusCodexChatUtils;
  const bridgeUrl = window.MEMO_NEXUS_CODEX_BRIDGE_URL || "http://127.0.0.1:8787";
  const panel = document.getElementById("aiPanel");
  const scroll = panel?.querySelector(".ai-panel-scroll");
  if (!scroll) return;
  const standard = document.createElement("div"); standard.id = "aiStandardContent";
  [...scroll.children].forEach((node) => standard.append(node));
  const tabs = document.createElement("div"); tabs.className = "codex-mode-tabs"; tabs.setAttribute("role", "tablist");
  tabs.innerHTML = '<button id="standardAiTab" type="button" role="tab" aria-selected="true">通常AI</button><button id="codexChatTab" type="button" role="tab" aria-selected="false">Codex</button>';
  const view = document.createElement("section"); view.id = "codexChatView"; view.hidden = true; view.className = "codex-chat-view"; view.setAttribute("aria-label", "Codexチャット");
  view.innerHTML = '<div class="codex-status-row"><span id="codexConnectionStatus" class="ai-status-badge" data-state="unchecked">Codexに接続中</span><button id="codexNewChatBtn" type="button">新しい会話</button></div><p class="codex-local-note">この機能はPCのローカル連携を起動した時だけ使えます。本文は明示的に添付するまで送信しません。</p><div class="codex-attachment-actions"><button id="codexAttachNoteBtn" type="button">このメモを添付</button><button id="codexAttachSelectionBtn" type="button" hidden>選択範囲を添付</button></div><div id="codexAttachmentPreview" class="codex-attachment-preview" hidden></div><section class="ai-chat-section" aria-label="Codex会話"><div id="codexChatHistory" class="ai-chat-history"><p class="ai-chat-empty">メモ内容を送らずに会話を始められます。</p></div></section><label class="ai-field" for="codexChatInput"><span>Codexへのメッセージ</span><textarea id="codexChatInput" rows="4" placeholder="質問や依頼を入力"></textarea></label><div class="ai-request-actions"><button id="codexSendBtn" type="button">送信</button></div><p id="codexChatStatus" class="ai-generation-status" role="status" aria-live="polite">ローカル連携を確認しています。</p>';
  scroll.append(tabs, standard, view);
  const state = { active: false, busy: false, attachment: null, history: [], thread: null, currentNoteId: null };
  const $ = (id) => document.getElementById(id);
  function note() { return typeof currentNote === "function" ? currentNote() : null; }
  function setActive(active) { state.active = active; standard.hidden = active; view.hidden = !active; $("standardAiTab").setAttribute("aria-selected", String(!active)); $("codexChatTab").setAttribute("aria-selected", String(active)); if (active) { refreshForNote(); checkHealth(); } }
  function render() { const history = $("codexChatHistory"); history.replaceChildren(); if (!state.history.length) history.innerHTML = '<p class="ai-chat-empty">メモ内容を送らずに会話を始められます。</p>'; state.history.forEach((message) => { const item = document.createElement("article"); item.className = `ai-chat-message ${message.role}`; const content = document.createElement("pre"); content.textContent = message.content || "生成中…"; item.append(content); if (message.role === "assistant" && message.content) { const copy = document.createElement("button"); copy.type = "button"; copy.textContent = "コピー"; copy.addEventListener("click", () => writeTextToClipboard(message.content, { fallbackCopyText })); item.append(copy); } history.append(item); }); history.scrollTop = history.scrollHeight;
    const preview = $("codexAttachmentPreview"); preview.hidden = !state.attachment; preview.textContent = state.attachment ? `${state.attachment.kind === "selection" ? "選択範囲" : "このメモ"}を添付予定${state.attachment.truncated ? "（末尾を省略）" : ""}` : ""; if (state.attachment) { const remove = document.createElement("button"); remove.type = "button"; remove.textContent = "添付を取り消す"; remove.addEventListener("click", () => { state.attachment = null; render(); }); preview.append(" ", remove); }
    $("codexSendBtn").disabled = state.busy; }
  async function checkHealth() { try { const response = await fetch(`${bridgeUrl}/health`); const data = await response.json(); const badge = $("codexConnectionStatus"); badge.textContent = data.ok ? "接続済み" : "ローカル連携が起動していません"; badge.dataset.state = data.ok ? "connected" : "unavailable"; $("codexChatStatus").textContent = data.ok ? "接続済みです。会話は読み取り専用です。" : "この機能はPCのローカル連携を起動した時だけ使えます。"; } catch { $("codexConnectionStatus").textContent = "ローカル連携が起動していません"; $("codexConnectionStatus").dataset.state = "unavailable"; $("codexChatStatus").textContent = "npm run codex:bridge を起動してください。"; } }
  async function persistThread(thread) { const current = note(); if (!current || !thread?.threadId) return; current.codexChat = { threadId: thread.threadId, lastUsedAt: new Date().toISOString(), title: thread.title || "Codex会話" }; await putNote(current); notes = await getAllNotes(); currentId = current.id; }
  function refreshForNote() { const current = note(); state.currentNoteId = current?.id || null; state.thread = normalizeThreadInfo(current?.codexChat); state.history = []; state.attachment = null; const selection = window.getSelection()?.toString().trim(); $("codexAttachSelectionBtn").hidden = !selection; render(); }
  async function send() { if (state.busy) return; const text = $("codexChatInput").value.trim(); if (!text) return; state.busy = true; const user = { role: "user", content: text }; const answer = { role: "assistant", content: "" }; state.history.push(user, answer); render(); $("codexChatStatus").textContent = "Codexに接続中…";
    try { const request = { message: formatPrompt(text, state.attachment), threadId: state.thread?.threadId || "" }; const response = await fetch(`${bridgeUrl}/chat`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(request) }); if (!response.ok) throw new Error((await response.json()).error); const reader = response.body.getReader(); const decoder = new TextDecoder(); let buffer = ""; while (true) { const { value, done } = await reader.read(); if (done) break; buffer += decoder.decode(value, { stream: true }); const parts = buffer.split("\n\n"); buffer = parts.pop(); parts.forEach((part) => { if (!part.startsWith("data: ")) return; const event = JSON.parse(part.slice(6)); if (event.type === "thread") { state.thread = { threadId: event.threadId, title: "Codex会話" }; persistThread(state.thread); } if (event.type === "delta") { answer.content += event.delta; render(); } }); } $("codexChatStatus").textContent = "回答完了"; $("codexChatInput").value = ""; state.attachment = null; }
    catch (error) { $("codexConnectionStatus").textContent = "エラー"; $("codexConnectionStatus").dataset.state = "error"; $("codexChatStatus").textContent = error.message || "Codexとの通信に失敗しました。"; if (!answer.content) state.history.pop(); }
    finally { state.busy = false; render(); }
  }
  $("standardAiTab").addEventListener("click", () => setActive(false)); $("codexChatTab").addEventListener("click", () => setActive(true)); $("codexAttachNoteBtn").addEventListener("click", () => { const current = note(); state.attachment = buildAttachment(current, "note"); render(); }); $("codexAttachSelectionBtn").addEventListener("click", () => { state.attachment = buildAttachment({ title: note()?.title, selection: window.getSelection()?.toString() }, "selection"); render(); }); $("codexSendBtn").addEventListener("click", send); $("codexNewChatBtn").addEventListener("click", () => { if (state.thread && !confirm("現在のメモを新しいCodex会話へ切り替えます。既存スレッドは削除しません。")) return; state.thread = null; state.history = []; render(); });
  window.MemoNexusCodexChat = { onMemoChanged: refreshForNote }; refreshForNote();
})();
