(function () {
  "use strict";
  const { buildAttachment, extractEditorSelection, formatPrompt, normalizeThreadInfo, withCodexThread, withoutCodexThread } = window.MemoNexusCodexChatUtils;
  const bridgeUrl = window.MEMO_NEXUS_CODEX_BRIDGE_URL || "http://127.0.0.1:8787";
  const panel = document.getElementById("aiPanel"); const scroll = panel?.querySelector(".ai-panel-scroll"); const editor = document.getElementById("editor"); if (!scroll) return;
  const standard = document.createElement("div"); standard.id = "aiStandardContent"; [...scroll.children].forEach((node) => standard.append(node));
  const tabs = document.createElement("div"); tabs.className = "codex-mode-tabs"; tabs.setAttribute("role", "tablist"); tabs.innerHTML = '<button id="standardAiTab" type="button" role="tab" aria-selected="true">通常AI</button><button id="codexChatTab" type="button" role="tab" aria-selected="false">Codex</button>';
  const view = document.createElement("section"); view.id = "codexChatView"; view.hidden = true; view.className = "codex-chat-view"; view.setAttribute("aria-label", "Codexチャット"); view.innerHTML = '<div class="codex-status-row"><span id="codexConnectionStatus" class="ai-status-badge" data-state="unchecked">Codexに接続中</span><button id="codexNewChatBtn" type="button">新しい会話</button></div><p class="codex-local-note">ブラウザとブリッジの接続だけがローカルです。入力と明示添付した内容は、ログイン済みCodexを通じてOpenAIのサービスへ送信されます。本文は添付するまで送信しません。</p><div class="codex-attachment-actions"><button id="codexAttachNoteBtn" type="button">このメモを添付</button><button id="codexAttachSelectionBtn" type="button" hidden>選択範囲を添付</button></div><div id="codexAttachmentPreview" class="codex-attachment-preview" hidden></div><section class="ai-chat-section" aria-label="Codex会話"><div id="codexChatHistory" class="ai-chat-history"><p class="ai-chat-empty">メモ内容を送らずに会話を始められます。</p></div></section><label class="ai-field" for="codexChatInput"><span>Codexへのメッセージ</span><textarea id="codexChatInput" rows="4" placeholder="質問や依頼を入力"></textarea></label><div class="ai-request-actions"><button id="codexSendBtn" type="button">送信</button></div><p id="codexChatStatus" class="ai-generation-status" role="status" aria-live="polite">ローカル連携を確認しています。</p>';
  scroll.append(tabs, standard, view);
  const state = { active: false, busyRequestNoteId: null, currentNoteId: null, selectionSnapshot: "", conversations: new Map() };
  const $ = (id) => document.getElementById(id); const note = () => typeof currentNote === "function" ? currentNote() : null;
  function conversation(noteId = state.currentNoteId) { if (!noteId) return { thread: null, history: [], attachment: null }; if (!state.conversations.has(noteId)) state.conversations.set(noteId, { thread: normalizeThreadInfo(notes.find((item) => item.id === noteId)?.codexChat), history: [], attachment: null }); return state.conversations.get(noteId); }
  function isCurrent(noteId) { return state.currentNoteId === noteId; }
  function render() { const current = conversation(); const history = $("codexChatHistory"); history.replaceChildren(); if (!current.history.length) history.innerHTML = '<p class="ai-chat-empty">メモ内容を送らずに会話を始められます。</p>'; current.history.forEach((message) => { const item = document.createElement("article"); item.className = `ai-chat-message ${message.role}`; const content = document.createElement("pre"); content.textContent = message.content || "生成中…"; item.append(content); if (message.role === "assistant" && message.content) { const copy = document.createElement("button"); copy.type = "button"; copy.textContent = "コピー"; copy.addEventListener("click", () => writeTextToClipboard(message.content, { fallbackCopyText })); item.append(copy); } history.append(item); });
    const preview = $("codexAttachmentPreview"); preview.hidden = !current.attachment; preview.textContent = current.attachment ? `${current.attachment.kind === "selection" ? "選択範囲" : "このメモ"}を添付予定` : ""; if (current.attachment) { const remove = document.createElement("button"); remove.type = "button"; remove.textContent = "添付を取り消す"; remove.addEventListener("click", () => { current.attachment = null; render(); }); preview.append(" ", remove); } $("codexAttachSelectionBtn").hidden = !state.selectionSnapshot; $("codexAttachSelectionBtn").disabled = !state.selectionSnapshot; $("codexSendBtn").disabled = Boolean(state.busyRequestNoteId); }
  function captureSelection() { if (!isCurrent(note()?.id)) return; state.selectionSnapshot = extractEditorSelection(editor); if (state.active) render(); }
  async function saveForNote(noteId, updater) { const existing = notes.find((item) => item.id === noteId); if (!existing || existing.deletedAt) return null; const updated = updater(existing); await putNote(updated); notes = await getAllNotes(); return updated; }
  async function checkHealth() { try { const response = await fetch(`${bridgeUrl}/health`); const data = await response.json(); $("codexConnectionStatus").textContent = data.ok ? "接続済み" : "ローカル連携が起動していません"; $("codexConnectionStatus").dataset.state = data.ok ? "connected" : "unavailable"; $("codexChatStatus").textContent = data.ok ? "接続済みです。会話内容はCodexへ送信されます。" : "この機能はPCのローカル連携を起動した時だけ使えます。"; } catch { $("codexConnectionStatus").textContent = "ローカル連携が起動していません"; $("codexConnectionStatus").dataset.state = "unavailable"; $("codexChatStatus").textContent = "npm run codex:bridge を起動してください。"; } }
  function refreshForNote() { const nextNoteId = note()?.id || null; if (nextNoteId !== state.currentNoteId) state.selectionSnapshot = ""; state.currentNoteId = nextNoteId; conversation(); render(); }
  function setActive(active) { state.active = active; standard.hidden = active; view.hidden = !active; $("standardAiTab").setAttribute("aria-selected", String(!active)); $("codexChatTab").setAttribute("aria-selected", String(active)); if (active) { captureSelection(); checkHealth(); } }
  async function send() { if (state.busyRequestNoteId) return; const text = $("codexChatInput").value.trim(); const requestNoteId = state.currentNoteId; if (!text || !requestNoteId) return; const requestConversation = conversation(requestNoteId); const answer = { role: "assistant", content: "" }; state.busyRequestNoteId = requestNoteId; requestConversation.history.push({ role: "user", content: text }, answer); render();
    try { const response = await fetch(`${bridgeUrl}/chat`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ message: formatPrompt(text, requestConversation.attachment), threadId: requestConversation.thread?.threadId || "" }) }); if (!response.ok) throw new Error((await response.json()).error); const reader = response.body.getReader(); const decoder = new TextDecoder(); let buffer = ""; while (true) { const { value, done } = await reader.read(); if (done) break; buffer += decoder.decode(value, { stream: true }); const parts = buffer.split("\n\n"); buffer = parts.pop(); for (const part of parts) { if (!part.startsWith("data: ")) continue; const event = JSON.parse(part.slice(6)); if (event.type === "thread") { requestConversation.thread = { threadId: event.threadId, title: "Codex会話" }; await saveForNote(requestNoteId, (existing) => withCodexThread(existing, requestConversation.thread)); } else if (event.type === "delta") answer.content += event.delta; else if (event.type === "error") throw new Error(event.error || "Codexとの通信に失敗しました。"); if (isCurrent(requestNoteId)) render(); } } if (isCurrent(requestNoteId)) { $("codexChatStatus").textContent = "回答完了"; $("codexChatInput").value = ""; requestConversation.attachment = null; } }
    catch (error) { if (isCurrent(requestNoteId)) { $("codexConnectionStatus").textContent = "エラー"; $("codexConnectionStatus").dataset.state = "error"; $("codexChatStatus").textContent = error.message || "Codexとの通信に失敗しました。"; } if (!answer.content) requestConversation.history.pop(); }
    finally { state.busyRequestNoteId = null; render(); }
  }
  $("standardAiTab").addEventListener("click", () => setActive(false)); $("codexChatTab").addEventListener("click", () => setActive(true)); editor?.addEventListener("select", captureSelection); editor?.addEventListener("keyup", captureSelection); editor?.addEventListener("mouseup", captureSelection); $("codexAttachNoteBtn").addEventListener("click", () => { const current = note(); conversation().attachment = buildAttachment({ ...current, id: current?.id, title: typeof titleInput !== "undefined" ? titleInput.value : current?.title, body: editor?.value ?? current?.body }, "note"); render(); }); $("codexAttachSelectionBtn").addEventListener("click", () => { conversation().attachment = buildAttachment({ title: note()?.title, selection: state.selectionSnapshot }, "selection"); render(); }); $("codexSendBtn").addEventListener("click", send);
  $("codexNewChatBtn").addEventListener("click", async () => { const current = note(); const currentConversation = conversation(); if (!current || !currentConversation.thread || !confirm("現在のメモを新しいCodex会話へ切り替えます。既存スレッドは削除しません。")) return; try { await saveForNote(current.id, withoutCodexThread); currentConversation.thread = null; currentConversation.history = []; render(); } catch (error) { $("codexChatStatus").textContent = `新しい会話へ切り替えられませんでした: ${error.message}`; } });
  window.MemoNexusCodexChat = { onMemoChanged: refreshForNote }; refreshForNote();
})();
