(function () {
  "use strict";
  const { buildAttachment, buildBridgeRequestHeaders, clearSessionBridgeToken, createCodexChatState, extractEditorSelection, formatPrompt, loadSessionBridgeToken, normalizeBridgeToken, readCodexEventStream, saveSessionBridgeToken, withCodexThread, withoutCodexThread } = window.MemoNexusCodexChatUtils;
  const bridgeUrl = window.MEMO_NEXUS_CODEX_BRIDGE_URL || "http://127.0.0.1:8787";
  const panel = document.getElementById("aiPanel"); const scroll = panel?.querySelector(".ai-panel-scroll"); const editor = document.getElementById("editor"); if (!scroll) return;
  const standard = document.createElement("div"); standard.id = "aiStandardContent"; [...scroll.children].forEach((node) => standard.append(node));
  const tabs = document.createElement("div"); tabs.className = "codex-mode-tabs"; tabs.setAttribute("role", "tablist"); tabs.innerHTML = '<button id="standardAiTab" type="button" role="tab" aria-selected="true">通常AI</button><button id="codexChatTab" type="button" role="tab" aria-selected="false">Codex</button>';
  const view = document.createElement("section"); view.id = "codexChatView"; view.hidden = true; view.className = "codex-chat-view"; view.setAttribute("aria-label", "Codexチャット"); view.innerHTML = '<div class="codex-status-row"><span id="codexConnectionStatus" class="ai-status-badge" data-state="unchecked">Codexに接続中</span><button id="codexNewChatBtn" type="button">新しい会話</button></div><p class="codex-local-note">公開版を開いている場合も、接続先はこのPCの127.0.0.1です。入力と明示添付した内容は、ログイン済みCodexを通じてOpenAIのサービスへ送信されます。本文は添付するまで送信しません。</p><label class="ai-field" for="codexBridgeTokenInput"><span>ブリッジ接続トークン</span><input id="codexBridgeTokenInput" type="password" autocomplete="off" spellcheck="false" placeholder="ターミナルへ設定したトークン"></label><div class="ai-request-actions"><button id="codexSaveTokenBtn" type="button">トークンを設定</button><button id="codexClearTokenBtn" type="button">トークンを消去</button></div><p class="codex-local-note">トークンはこのタブのsessionStorageだけに保持し、メモやバックアップへ保存しません。入力値は画面へ再表示しません。</p><div class="codex-attachment-actions"><button id="codexAttachNoteBtn" type="button">このメモを添付</button><button id="codexAttachSelectionBtn" type="button" hidden>選択範囲を添付</button></div><div id="codexAttachmentPreview" class="codex-attachment-preview" hidden></div><section class="ai-chat-section" aria-label="Codex会話"><div id="codexChatHistory" class="ai-chat-history"><p class="ai-chat-empty">メモ内容を送らずに会話を始められます。</p></div></section><label class="ai-field" for="codexChatInput"><span>Codexへのメッセージ</span><textarea id="codexChatInput" rows="4" placeholder="質問や依頼を入力"></textarea></label><div class="ai-request-actions"><button id="codexSendBtn" type="button">送信</button></div><p id="codexChatStatus" class="ai-generation-status" role="status" aria-live="polite">ローカル連携を確認しています。</p><details class="codex-connection-help"><summary>接続できない場合</summary><ol><li>Codex CLIへログイン済みか</li><li>npm run codex:bridgeを起動しているか</li><li>ターミナルと入力欄のトークンが一致するか</li><li>ブラウザのローカルネットワークアクセスを拒否していないか</li><li>公開Originがブリッジで許可されているか</li></ol></details>';
  scroll.append(tabs, standard, view);
  const stateController = createCodexChatState((noteId) => notes.find((item) => item.id === noteId)?.codexChat);
  const state = stateController.state;
  const $ = (id) => document.getElementById(id); const note = () => typeof currentNote === "function" ? currentNote() : null;
  function tokenStorage() { try { return window.sessionStorage; } catch { return null; } }
  let bridgeToken = loadSessionBridgeToken(tokenStorage());
  const conversation = stateController.conversation;
  function isCurrent(noteId) { return state.currentNoteId === noteId; }
  function render() { const current = conversation(); const history = $("codexChatHistory"); history.replaceChildren(); if (!current.history.length) history.innerHTML = '<p class="ai-chat-empty">メモ内容を送らずに会話を始められます。</p>'; current.history.forEach((message) => { const item = document.createElement("article"); item.className = `ai-chat-message ${message.role}`; const content = document.createElement("pre"); content.textContent = message.content || "生成中…"; item.append(content); if (message.role === "assistant" && message.content) { const copy = document.createElement("button"); copy.type = "button"; copy.textContent = "コピー"; copy.addEventListener("click", () => writeTextToClipboard(message.content, { fallbackCopyText })); item.append(copy); } history.append(item); });
    const preview = $("codexAttachmentPreview"); preview.hidden = !current.attachment; preview.textContent = current.attachment ? `${current.attachment.kind === "selection" ? "選択範囲" : "このメモ"}を添付予定` : ""; if (current.attachment) { const remove = document.createElement("button"); remove.type = "button"; remove.textContent = "添付を取り消す"; remove.addEventListener("click", () => { current.attachment = null; render(); }); preview.append(" ", remove); } $("codexAttachSelectionBtn").hidden = !state.selectionSnapshot; $("codexAttachSelectionBtn").disabled = !state.selectionSnapshot; $("codexSendBtn").disabled = Boolean(state.busyRequestNoteId) || !bridgeToken; $("codexClearTokenBtn").disabled = !bridgeToken; }
  function captureSelection() { if (!isCurrent(note()?.id)) return; state.selectionSnapshot = extractEditorSelection(editor); if (state.active) render(); }
  async function saveForNote(noteId, updater) { return enqueueCodexThreadSave(noteId, updater); }
  function setConnectionState(label, stateName, message) { $("codexConnectionStatus").textContent = label; $("codexConnectionStatus").dataset.state = stateName; $("codexChatStatus").textContent = message; }
  function invalidateBridgeToken(message = "トークンが一致しません。再入力してください。") { bridgeToken = ""; clearSessionBridgeToken(tokenStorage()); $("codexBridgeTokenInput").value = ""; setConnectionState("トークン不一致", "auth-error", message); render(); }
  async function checkHealth() { try { const response = await fetch(`${bridgeUrl}/health`, { headers: buildBridgeRequestHeaders(bridgeToken) }); if (response.status === 401) return invalidateBridgeToken(); const data = await response.json(); if (!bridgeToken && data.authRequired) { setConnectionState("トークン未入力", "auth-required", "ブリッジ接続トークンが必要です。"); return; } if (response.status === 503 || data.status === "unavailable") { setConnectionState("エラー", "error", "Codex App Serverの初期化に失敗しました。Codex CLIのログイン状態を確認してください。"); return; } setConnectionState(data.ok ? "接続済み" : "エラー", data.ok ? "connected" : "error", data.ok ? "接続済みです。会話内容はCodexへ送信されます。" : "Codexローカル連携を利用できません。"); } catch { setConnectionState("ローカル連携へ接続できません", "unavailable", "ブリッジ未起動、公開Origin未許可、またはブラウザのローカルネットワークアクセス拒否が考えられます。下の確認手順を確認してください。"); } }
  function refreshForNote(changedNote = note()) { stateController.switchNote(changedNote?.id || null); render(); }
  function setActive(active) { state.active = active; standard.hidden = active; view.hidden = !active; $("standardAiTab").setAttribute("aria-selected", String(!active)); $("codexChatTab").setAttribute("aria-selected", String(active)); if (active) { captureSelection(); checkHealth(); } }
  async function send() { if (state.busyRequestNoteId) return; if (!bridgeToken) { setConnectionState("トークン未入力", "auth-required", "ブリッジ接続トークンが必要です。"); return; } const text = $("codexChatInput").value.trim(); const requestNoteId = state.currentNoteId; if (!text || !requestNoteId) return; const requestConversation = stateController.startRequest(requestNoteId); if (!requestConversation) return; const answer = { role: "assistant", content: "" }; requestConversation.history.push({ role: "user", content: text }, answer); render();
    try { const response = await fetch(`${bridgeUrl}/chat`, { method: "POST", headers: buildBridgeRequestHeaders(bridgeToken, true), body: JSON.stringify({ message: formatPrompt(text, requestConversation.attachment), threadId: requestConversation.thread?.threadId || "" }) }); if (response.status === 401) { const error = new Error("トークンが一致しません。再入力してください。"); error.authFailure = true; invalidateBridgeToken(error.message); throw error; } if (!response.ok) throw new Error((await response.json()).error); await readCodexEventStream(response.body.getReader(), async (event) => { if (event.type === "thread") { requestConversation.thread = { threadId: event.threadId, title: "Codex会話" }; await saveForNote(requestNoteId, (existing) => withCodexThread(existing, requestConversation.thread)); } else if (event.type === "delta") answer.content += event.delta; if (isCurrent(requestNoteId)) render(); }); if (isCurrent(requestNoteId)) { $("codexChatStatus").textContent = "回答完了"; $("codexChatInput").value = ""; requestConversation.attachment = null; } }
    catch (error) { if (isCurrent(requestNoteId) && !error.authFailure) { $("codexConnectionStatus").textContent = "エラー"; $("codexConnectionStatus").dataset.state = "error"; $("codexChatStatus").textContent = error.message || "ストリーミング中に接続が切れました。ブリッジとブラウザ権限を確認してください。"; } if (!answer.content) requestConversation.history.pop(); }
    finally { stateController.finishRequest(requestNoteId); render(); }
  }
  $("standardAiTab").addEventListener("click", () => setActive(false)); $("codexChatTab").addEventListener("click", () => setActive(true)); editor?.addEventListener("select", captureSelection); editor?.addEventListener("keyup", captureSelection); editor?.addEventListener("mouseup", captureSelection); $("codexSaveTokenBtn").addEventListener("click", async () => { const input = $("codexBridgeTokenInput"); const normalized = normalizeBridgeToken(input.value); input.value = ""; if (!normalized) { setConnectionState("トークン未入力", "auth-required", "32文字以上で空白を含まないランダムなトークンを入力してください。"); return; } bridgeToken = saveSessionBridgeToken(tokenStorage(), normalized) || normalized; render(); setConnectionState("Codexに接続中", "unchecked", "トークンを確認しています。"); await checkHealth(); }); $("codexClearTokenBtn").addEventListener("click", () => invalidateBridgeToken("ブリッジ接続トークンを消去しました。再入力してください。")); $("codexBridgeTokenInput").addEventListener("keydown", (event) => { if (event.key === "Enter") { event.preventDefault(); $("codexSaveTokenBtn").click(); } }); $("codexAttachNoteBtn").addEventListener("click", () => { const current = note(); conversation().attachment = buildAttachment({ ...current, id: current?.id, title: typeof titleInput !== "undefined" ? titleInput.value : current?.title, body: editor?.value ?? current?.body }, "note"); render(); }); $("codexAttachSelectionBtn").addEventListener("click", () => { conversation().attachment = buildAttachment({ title: note()?.title, selection: state.selectionSnapshot }, "selection"); render(); }); $("codexSendBtn").addEventListener("click", send);
  $("codexNewChatBtn").addEventListener("click", async () => { const current = note(); const currentConversation = conversation(); if (!current || !currentConversation.thread || !confirm("現在のメモを新しいCodex会話へ切り替えます。既存スレッドは削除しません。")) return; try { await saveForNote(current.id, withoutCodexThread); currentConversation.thread = null; currentConversation.history = []; render(); } catch (error) { $("codexChatStatus").textContent = `新しい会話へ切り替えられませんでした: ${error.message}`; } });
  window.MemoNexusCodexChat = { onMemoChanged: refreshForNote }; refreshForNote();
})();
